import '@/styles/globals.css';
import '@mantine/charts/styles.css';

import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import { Toaster } from 'react-hot-toast';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <Toaster />
                <MantineProvider>{children}</MantineProvider>
            </body>
        </html>
    );
}
